name: Cargo Build & Test

on:
  pull_request:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
        continue-on-error: true
      - run: cargo build --verbose
        continue-on-error: true
      - run: cargo test --verbose
        continue-on-error: true
